#ifndef ECU_CONFIG_AGROBOT_ATV_H_
#define ECU_CONFIG_AGROBOT_ATV_H_

#define USE_CTRL_TRACTION
#define USE_CTRL_STEERING

#define USE_SRV_UI_SERIAL
#define USE_SRV_COM_CAN
#define USE_SRV_UI_BT
// #define USE_SRV_UI_LCD

#define USE_DD_DC_MOTOR
// #define USE_DD_JOYSTICK
// #define USE_DD_ENCODER

#define USE_ED_CAN_MCP
#define USE_ED_L298
// #define USE_ED_ESC
// #define USE_ED_BUZZER

#define SRV_UI_BT_ROLLBACK_DEFAULT SRV_UI_BT_ROLLBACK_DISABLED
#define CTRL_TRACTION_TARGET_MODE CTRL_TRACTION_TARGET_MODE_BT
#define CTRL_STEERING_TARGET_MODE CTRL_STEERING_TARGET_MODE_BT

#define DD_DC_MOTOR_MAX_POWER 255
#define DD_DC_MOTOR_MIN_POWER -255

#define ED_L298_IN_1_PIN_LIST { 8 , 4}
#define ED_L298_IN_2_PIN_LIST { 7, 5}
#define ED_L298_EN_PIN_LIST { 9, 6}

#define CAN0_INT 2 // Set INT to pin 2
#define CAN0_CS 10 // Set CS to pin 2

#define TX_CAN_ID_NR_OF 0
#define TX_CAN_ID_LIST {}
#define RX_CAN_ID_NR_OF 3
#define RX_CAN_ID_LIST {CAN_ID_UI_BT_CHASSIS, CAN_ID_UI_BT}

#endif /* ECU_CONFIG_OMNIWHEEL_ */