#ifndef ECU_CONFIG_OMNIWHEEL_H
#define ECU_CONFIG_OMNIWHEEL_H

#define ECU_OMNI_WHEEL_FL 3
#define ECU_OMNI_WHEEL_FR 4
#define ECU_OMNI_WHEEL_BL 5
#define ECU_OMNI_WHEEL_BR 6
#define ECU_OMNI_WHEEL_ALL 7

#define USE_CTRL_TRACTION
#define USE_CTRL_STEERING

#define USE_SRV_UI_SERIAL
#define USE_SRV_COM_CAN
// #define USE_SRV_UI_BT
// #define USE_SRV_UI_LCD

#define USE_DD_DC_MOTOR
// #define USE_DD_JOYSTICK
#define USE_DD_ENCODER

#define USE_ED_CAN_MCP
#define USE_ED_L298
// #define USE_ED_ESC
// #define USE_ED_BUZZER

#define SRV_UI_BT_ROLLBACK_DEFAULT SRV_UI_BT_ROLLBACK_DISABLED
#define CTRL_TRACTION_TARGET_MODE CTRL_TRACTION_TARGET_MODE_CAN
#define CTRL_STEERING_TARGET_MODE CTRL_STEERING_TARGET_MODE_CAN
#define CTRL_STEERING_FB_MODE CTRL_STEERING_FB_MODE_TIMER
#define CTRL_TRACTION_FB_MODE CTRL_TRACTION_FB_MODE_TIMER
#define CTRL_TRACTION_OP_MODE CTRL_TRACTION_OP_MODE_STEP
#define CTRL_STEERING_OP_MODE CTRL_STEERING_OP_MODE_STEP

#define DD_DC_MOTOR_MAX_POWER 80
#define DD_DC_MOTOR_MIN_POWER -80

#define ED_L298_IN_1_PIN_LIST { 6, 2}
#define ED_L298_IN_2_PIN_LIST { 7, 4}
#define ED_L298_EN_PIN_LIST { 5, 3}

#define CAN0_INT 8 // Set INT to pin 2
#define CAN0_CS 10 // Set CS to pin 2

#define TX_CAN_ID_NR_OF 0
#define TX_CAN_ID_LIST {}
#define RX_CAN_ID_NR_OF 3
#define RX_CAN_ID_LIST {CAN_ID_UI_BT_CHASSIS, CAN_ID_UI_BT}

#endif /* ECU_CONFIG_OMNIWHEEL_ */